### ISSUE TITLE
Does not work in chrome console

### ISSUE THREAD

**Issue by Xantis52** [frumsy/sweeper#1]
Is it supposed to? If not, instructions?

**Comment by otomist** [comment]
I added instruction to the README. Tell me if that works. It should.

**Comment by Xantis52** [comment]
Thank you very much! It works, but it does not flag mines. Is it supposed to be that way?

**Comment by otomist** [comment]
It's not made to add flags but it wouldn't be hard to add.

**Comment by Xantis52** [comment]
Sorry, I'm not complaining, this is amazing! It'd be cool if you could add it, but this is still great without it!

**Comment by otomist** [comment]
I can probably make time to add it. You're free to try too. If you make a new Issue with enhancement tag I'll be more likely to get to it later.
